from pathlib import Path

ROOT_DIR = Path(__file__).parent.parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icon.png'

BIG_FONT_SIZE = 38
MIDIUM_FONT_SIZE = 22
SMALL_FONT_SIZE = 16
TEXT_MARGIN = 15

PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270' 
